# -*- coding: utf-8 -*-
"""Decision Trees.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHGBkkmXUMkNDIfckjst0Tzuxvw4FyKi
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# 1. ЗАГРУЗКА ДАННЫХ
try:
    df = pd.read_excel('Файл')
    print("Файл")
except:
    # Если файла под рукой нет, создаем данные  вручную
    data = {
        'IELTS': [9.0, 8.5, 5.5, 5.0, 7.0, 6.5],
        'SAT': [1600, 1200, 700, 700, 1100, 1000],
        'Motivation': [1, 1, 1, 0, 1, 0], # 1 - high, 0 - low
        'Accepted': [1, 1, 0, 0, 1, 0]    # 1 - да, 0 - нет
    }
    df = pd.DataFrame(data)
    print("Используются тестовые данные.")

# 2. РАСЧЕТ СРЕДНЕГО ЗНАЧЕНИЯ
print(f"\nСредний балл SAT: {df['SAT'].mean()}")

# 3. ФУНКЦИЯ ДЛЯ РАСЧЕТА ЗАГРЯЗНЕННОСТИ (Энтропия)
def calculate_entropy(y):
    if len(y) == 0: return 0
    proportions = y.value_counts(normalize=True)
    return -np.sum([p * np.log2(p) for p in proportions if p > 0])

# 4. ЛОГИКА РАЗДЕЛЕНИЯ
threshold = 1000
left_branch = df[df['SAT'] > threshold]
right_branch = df[df['SAT'] <= threshold]

ent_left = calculate_entropy(left_branch['Accepted'])
ent_right = calculate_entropy(right_branch['Accepted'])

print(f"Загрязненность левой ветки (SAT > {threshold}): {ent_left:.4f}")
print(f"Загрязненность правой ветки (SAT <= {threshold}): {ent_right:.4f}")

# 5. ПОСТРОЕНИЕ ДЕРЕВА (Визуализация)
X = df[['IELTS', 'SAT', 'Motivation']]
y = df['Accepted']

clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(X, y)

plt.figure(figsize=(10, 6))
plot_tree(clf, feature_names=X.columns, class_names=['Нет', 'Да'], filled=True)
plt.show()